# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('core', '0003_auto_20170612_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
