"""
Django settings for radhr project.

Generated by 'django-admin startproject' using Django 1.9.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3&y_w*ke50vou+fh*0lhhde8qr-%erb1^cv-3^4er(dpyr$wam'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

################################################################################
## Email: Configure SMTP Settings.                                            ##
################################################################################
EMAIL_HOST          = 'smtp.sendgrid.com'
EMAIL_HOST_USER     = 'radhr'
EMAIL_MAIN          = 'noreply@radhr.io'
EMAIL_HOST_PASSWORD = 'rave-b0lster-shirk'
EMAIL_PORT          = 587
EMAIL_USER_TLS      = True

"""
## To test this run in #> python manage.py shell
from django.conf import settings
from django.core.mail import send_mail

send_mail("subject", "here is the message", settings.EMAIL_MAIN, ["bnicoll@gmail.com"], fail_silently=False)
"""

ACCOUNT_AUTHENTICATION_METHOD           = "username_email"
ACCOUNT_EMAIL_REQUIRED                  = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS  = 7
ACCOUNT_EMAIL_VERIFICATION              = "mandatory"

################################################################################
## Applications: Install Required Applications.                               ##
################################################################################
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ## Wagtail : CMS Requirements                                             ##
    'wagtail.wagtailforms',
    'wagtail.wagtailredirects',
    'wagtail.wagtailembeds',
    'wagtail.wagtailsites',
    'wagtail.wagtailusers',
    'wagtail.wagtailsnippets',
    'wagtail.wagtaildocs',
    'wagtail.wagtailimages',
    'wagtail.wagtailsearch',
    'wagtail.wagtailadmin',
    'wagtail.wagtailcore',

    'modelcluster',
    'taggit',

    ## Third Party Applications : Djagno All Auth                             ##
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    ## ... include the providers you want to enable:                          ##
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',

    ## Third Party Applications  : General                                    ##
    'crispy_forms',
    'kawasemi.django',
    'markdown_deux',
    'pagedown',
    'simple_history',
    'storages',
    'betterforms',

    ## My Installed Applications                                              ##
    'accounts',
    'comments',
    'core',
    'lists',
    'posts'

]

################################################################################
## Accounts: All Auth Authentication Requirement.                             ##
################################################################################
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

################################################################################
## Crispy Forms: Theme Requirements.                                          ##
################################################################################
CRISPY_TEMPLATE_PACK = 'bootstrap3'


################################################################################
## Middleware: Requirements.                                                  ##
################################################################################
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    ## Third Party Middleware : Wagtail                                       ##
    'wagtail.wagtailcore.middleware.SiteMiddleware',
    'wagtail.wagtailredirects.middleware.RedirectMiddleware',

    ## Third Party Middleware : General                                       ##
    'simple_history.middleware.HistoryRequestMiddleware',

]

################################################################################
## Login URL: Set Login Requirements.                                         ##
################################################################################
LOGIN_URL = "/accounts/login/"


ROOT_URLCONF = 'radhr.urls'


################################################################################
## Wagtail: Configuration Settings.                                           ##
################################################################################
# This is the human-readable name of your Wagtail install
# which welcomes users upon login to the Wagtail admin.
WAGTAIL_SITE_NAME = 'RadHR'

# Override the search results template for wagtailsearch
# WAGTAILSEARCH_RESULTS_TEMPLATE = 'myapp/search_results.html'
# WAGTAILSEARCH_RESULTS_TEMPLATE_AJAX = 'myapp/includes/search_listing.html'

# Replace the search backend
#WAGTAILSEARCH_BACKENDS = {
#  'default': {
#    'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch2',
#    'INDEX': 'myapp'
#  }
#}

# Wagtail email notifications from address
# WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = 'wagtail@myhost.io'

# Wagtail email notification format
# WAGTAILADMIN_NOTIFICATION_USE_HTML = True

# If you want to use Embedly for embeds, supply a key
# (this key doesn't work, get your own!)
# WAGTAILEMBEDS_EMBEDLY_KEY = '253e433d59dc4d2xa266e9e0de0cb830'

# Reverse the default case-sensitive handling of tags
TAGGIT_CASE_INSENSITIVE = True

################################################################################
## Templates: Updated to use global templates.                                ##
################################################################################
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'radhr.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Melbourne'

USE_I18N = True

USE_L10N = True

USE_TZ = True

################################################################################
## Social Authentication: Provider Settings.                                  ##
################################################################################
## http://127.0.0.1:8000/accounts/facebook/login/callback/
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2.4',
    }
}

################################################################################
## Alert Notifications: Slack.                                                ##
################################################################################
KAWASEMI = {
    "CHANNELS": {
        "slack": {
            "_backend": "kawasemi.backends.slack.SlackChannel",
            "url": "https://hooks.slack.com/services/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",
            "icon_emoji": ":robot_face:",
            "channel": "#_alerts",
            "username": "RadBot",
        }
    }
}

AUTH_USER_MODULE = "auth.User"