"""
Django settings for radhr project.

Generated by 'django-admin startproject' using Django 1.9.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from .base import *
import datetime
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# Database - PRODUCTION
# if 'RDS_DB_NAME' in os.environ:
# 	DATABASES = {
# 	    'default': {
# 	        'ENGINE': 'django.db.backends.postgresql_psycopg2',
# 	        'NAME': os.environ['RDS_DB_NAME'],
# 	        'USER': os.environ['RDS_USERNAME'],
# 	        'PASSWORD': os.environ['RDS_PASSWORD'],
# 	        'HOST': os.environ['RDS_HOSTNAME'],
# 	        'PORT': os.environ['RDS_PORT'],
# 	    }
# 	}


################################################################################
## AWS: Amazon Web Services S3 Requirements.                                  ##
################################################################################
# AWS_STORAGE_BUCKET_NAME = 'radhr-prod'
# AWS_ACCESS_KEY_ID = "AKIAJCT77M2PYVJ3P3MQ"
# AWS_SECRET_ACCESS_KEY = "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"

# AWS_FILE_EXPIRE = 200
# AWS_PRELOAD_METADATA = True
# AWS_QUERYSTRING_AUTH = True

# DEFAULT_FILE_STORAGE = 'radhr.utils.MediaRootS3BotoStorage'
# STATICFILES_STORAGE = 'radhr.utils.StaticRootS3BotoStorage'
# S3DIRECT_REGION = 'ap-southeast-2'
# S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME

# # MEDIA
# MEDIA_URL = S_3 URL + 'media/' 
# MEDIA_ROOT = MEDIA_URL

# # STATIC
# STATIC_URL = S3_URL + 'static/'
# ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'


DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = "AKIAJE3WDF34OOOEOBSA"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "radhr-test-bucket"
AWS_QUERYSTRING_AUTH = False # This will make sure that the file URL does not have unnecessary parameters like your access key.
AWS_S3_CUSTOM_DOMAIN = AWS_STORAGE_BUCKET_NAME + ".s3.amazonaws.com"
#static media settings
STATIC_URL = 'https://' + AWS_STORAGE_BUCKET_NAME + ".s3.amazonaws.com/"
MEDIA_URL = STATIC_URL + ‘media/’
STATICFILES_DIRS = (
	os.path.join(BASE_DIR, "static"),
)
STATIC_ROOT = "staticfiles"
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.FileSystemFinder',
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# two_months = datetime.timedelta(days=61)
# date_two_months_later = datetime.date.today() + two_months
# expires = date_two_months_later.strftime("%A, %d %B %Y 20:00:00 GMT")

# AWS_HEADERS = {
# 	'Expires': expires,
# 	'Cache-Control': 'max-age=%d' % (int(two_months.total_seconds()), ),
# }